//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtlSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THelpDeskTicket
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> ticket_type_id { get; set; }
        public string description { get; set; }
        public Nullable<int> ticket_status_id { get; set; }
        public Nullable<int> team_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> comment_id { get; set; }
        public Nullable<int> audit_id { get; set; }
        public Nullable<System.DateTime> deadline { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public string metadata { get; set; }
        public Nullable<int> status_id { get; set; }
        public string remark { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string last_updated_by { get; set; }
        public Nullable<System.DateTime> last_updated_date { get; set; }
    }
}
