//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtlSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNtlWindowUnit
    {
        public int id { get; set; }
        public Nullable<int> window_id { get; set; }
        public Nullable<int> unit_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> total_usage { get; set; }
        public Nullable<int> detail_id { get; set; }
    }
}
