//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtlSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNtlJobOrder
    {
        public int id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string client_order_ref { get; set; }
        public Nullable<decimal> sub_total_price { get; set; }
        public Nullable<decimal> discount_fee { get; set; }
        public Nullable<decimal> tax_price { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string customer_name { get; set; }
        public string customer_street { get; set; }
        public string customer_street2 { get; set; }
        public Nullable<int> customer_zip_code { get; set; }
        public string customer_city { get; set; }
        public string customer_state { get; set; }
        public string customer_country { get; set; }
        public Nullable<int> odoo_sales_id { get; set; }
        public Nullable<int> odoo_status_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> batch_id { get; set; }
        public Nullable<int> detail_id { get; set; }
    }
}
