//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtlSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNtlSummaryItem
    {
        public int id { get; set; }
        public string name { get; set; }
        public string sku { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> used { get; set; }
        public Nullable<decimal> length { get; set; }
        public Nullable<decimal> width { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> detail_id { get; set; }

        public override String ToString() {
            return $"{name} {sku} {width} {height} {quantity} {used}";
        }
    }
}
